### ISSUE TITLE
onSuccess callback not returning publicToken.

### ISSUE THREAD

**Issue by jdbarrera** [burstware/expo-plaid-link#6]
The onSuccess callback is not returning the publicToken.  I only get an object with the metadata.  However, you can see it in the event URL.  This was working yesterday but stopped today suddenly.
![Capture](https://user-images.githubusercontent.com/25085187/115560833-9685e800-a27a-11eb-9a9b-a6672ca37146.PNG)

**Comment by chadlaughland** [comment]
Having the same issue here. Was working properly and all of a sudden is not returning the publicToken correctly. Logging the eventParams extracted from queryString.parse(event.url) reveals the publicToken key as: 

`plaidlink://connected?public_token: "public-sandbox-6a2064fe-8386-4126-9931-e3ce715a3330"`
rather than
`public_token: "public-sandbox-6a2064fe-8386-4126-9931-e3ce715a3330"`

Its parsing the key with the 'plaidlink://connected?' pre-pended. Not sure if Plaid changed the url scheme or if queryString is broken. 

I fixed it on my project by modifying line 31 of PlaidLink.tsx. Basically adding the replace regex onto the event.url passed to queryString.parse()
`const eventParams = queryString.parse(event.url.replace(/plaidlink:\/\/event|plaidlink:\/\/exit|plaidlink:\/\/connected/gi, ""))`

Not sure if thats the best way but it should get this working again for the moment.

**Comment by jdbarrera** [comment]
That's a clever fix! I ended up just ejecting and using Plaid's native component.  I'll have to try this though.  Thanks!

**Comment by udaraweerasinghege** [comment]
Bump on this. @JBaczuk do you have plans on integrating something like what @chadlaughland suggested?

**Comment by JBaczuk** [comment]
> Bump on this. @JBaczuk do you have plans on integrating something like what @chadlaughland suggested? 

Hi! Yes I would happily review a PR.

**Comment by udaraweerasinghege** [comment]
Awesome! Thanks for creating and maintaining this project! I created a PR here https://github.com/burstware/expo-plaid-link/pull/7

**Comment by JBaczuk** [comment]
Fixed in https://github.com/burstware/expo-plaid-link/pull/7. Published in versions `1.0.3` and above.
